apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-k8s
  template:
    metadata:
      labels:
        app: nestjs-k8s
    spec:
      containers:
      - name: nestjs-k8s
        image: drack112/nestjs-k8s
        ports:
            - containerPort: 3000
        volumeMounts:
            - name: nestjs-volume
              mountPath: /usr/src/app/.env
              subPath: .env
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
      volumes:
        - name: nestjs-volume
          configMap:
            name: nestjs-config
            items:
              - key: env
                path: .env
